name: Deploy

on:
  push:
    tags:
      - 'deploy*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
    - name: Deploy [Staging]
      run: echo "Execute the deproy script here."
      if: contains(github.ref, 'deploy-stg')
    - name: Deploy [Prod]
      if: contains(github.ref, 'deploy-prod')
