name: Deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-release*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
    - name: Deploy
      run: echo "Execute the deproy script here."