name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  set-release-note:
    name: Set Release Note
    runs-on: ubuntu-latest
    steps:
      - name: Get current data
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm install simple-git
      - uses: actions/github-script@v3
        id: create-release-note
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          release_name: Release ${{ steps.date.outputs.date }}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/script/prs.js`)
            const path = `${process.env.GITHUB_WORKSPACE}`
            return await script({github, path})
          result-encoding: string
      - name: Update Releasing Note
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.create-release-note.outputs.result}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}